### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mlemontx** [anzhiyu-c/hexo-theme-anzhiyu#22]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.6

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

我在 hexo g 的时候出现以下问题，

```text
ERROR 
TypeError: D:\Project\mlemontx-hexo-blog\blog\themes\anzhiyu\layout\includes\page\flink.pug:3
    1| #article-container
    2|   - let totalLinks = 0;
  > 3|   each item in site.data.link
    4|     - totalLinks += item.link_list.length
    5|   if totalLinks >= 50
    6|     #flink-banners

Cannot read property 'length' of undefined
    at eval (eval at wrap (D:\Project\mlemontx-hexo-blog\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1701:32)
    at eval (eval at wrap (D:\Project\mlemontx-hexo-blog\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1716:4)
    at template (eval at wrap (D:\Project\mlemontx-hexo-blog\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:12725:7)
    at _View._compiled (D:\Project\mlemontx-hexo-blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\Project\mlemontx-hexo-blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\Project\mlemontx-hexo-blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\Project\mlemontx-hexo-blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Project\mlemontx-hexo-blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Project\mlemontx-hexo-blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:490:10)
    at resume_ (_stream_readable.js:975:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

### 出现问题的网站 | Website

本地运行

**Comment by mlemontx** [comment]
是因为本地有个 link 的 md 文档，导致的该问题，删掉就 ok 了。
