### ISSUE TITLE
[Bug]: Waline评论区不显示

### ISSUE THREAD

**Issue by weekdaycare** [anzhiyu-c/hexo-theme-anzhiyu#8]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.0

### 使用的浏览器？ || What browse are you using?

Chrome

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

使用waline serveURL，地址格式正确，本地预览评论区不显示，控制台报错
```
Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.
    at yo (https://npm.elemecdn.com/@waline/client@2.10.0/dist/waline.js:1:52837)
    at patchProp (https://npm.elemecdn.com/@waline/client@2.10.0/dist/waline.js:1:58625)
    at x (https://npm.elemecdn.com/@waline/client@2.10.0/dist/waline.js:1:33676)
    at k (https://npm.elemecdn.com/@waline/client@2.10.0/dist/waline.js:1:33317)
    at g (https://npm.elemecdn.com/@waline/client@2.10.0/dist/waline.js:1:32742)
    at $e.s [as fn] (https://npm.elemecdn.com/@waline/client@2.10.0/dist/waline.js:1:38539)
    at $e.run (https://npm.elemecdn.com/@waline/client@2.10.0/dist/waline.js:1:10299)
    at T.e.update (https://npm.elemecdn.com/@waline/client@2.10.0/dist/waline.js:1:38803)
    at T (https://npm.elemecdn.com/@waline/client@2.10.0/dist/waline.js:1:38829)
    at L (https://npm.elemecdn.com/@waline/client@2.10.0/dist/waline.js:1:37175)
```

### 出现问题的网站 | Website

https://weekdaycare.cn/

**Comment by anzhiyu-c** [comment]
该问题已被修复
